CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "descripcion" text
);

CREATE TABLE "usuarios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombres" varchar NOT NULL,
  "apellidos" varchar NOT NULL,
  "correo" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "rol_id" int,
  "fecha_registro" datetime DEFAULT (now()),
  "estado" enum(activo,inactivo) DEFAULT 'activo'
);

CREATE TABLE "idiomas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "descripcion" text,
  "icono_url" varchar
);

CREATE TABLE "niveles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "orden" int NOT NULL
);

CREATE TABLE "lecciones" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idioma_id" int,
  "nivel_id" int,
  "titulo" varchar NOT NULL,
  "descripcion" text,
  "tipo_contenido" enum(video,audio,texto,interactivo) DEFAULT 'video',
  "url_contenido" varchar,
  "duracion_min" int,
  "orden" int NOT NULL
);

CREATE TABLE "evaluaciones" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "leccion_id" int,
  "titulo" varchar NOT NULL,
  "cantidad_preguntas" int,
  "duracion_min" int
);

CREATE TABLE "preguntas_evaluacion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "evaluacion_id" int,
  "enunciado" text NOT NULL,
  "tipo" enum(opcion_multiple,verdadero_falso,respuesta_abierta),
  "respuesta_correcta" varchar
);

CREATE TABLE "opciones_pregunta" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pregunta_id" int,
  "texto_opcion" varchar NOT NULL,
  "es_correcta" boolean DEFAULT false
);

CREATE TABLE "progreso_leccion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int,
  "leccion_id" int,
  "estado" enum(bloqueada,en_progreso,completada) DEFAULT 'bloqueada',
  "porcentaje_avance" decimal(5,2) DEFAULT 0,
  "tiempo_estudio_min" int DEFAULT 0,
  "fecha_inicio" datetime,
  "fecha_completado" datetime
);

CREATE TABLE "resultados_evaluacion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int,
  "evaluacion_id" int,
  "respuestas_correctas" int,
  "total_preguntas" int,
  "puntaje_porcentaje" decimal(5,2),
  "aprobada" boolean DEFAULT false,
  "estado" enum(pendiente,en_progreso,completada) DEFAULT 'pendiente',
  "fecha" datetime DEFAULT (now())
);

ALTER TABLE "usuarios" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lecciones" ADD FOREIGN KEY ("idioma_id") REFERENCES "idiomas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lecciones" ADD FOREIGN KEY ("nivel_id") REFERENCES "niveles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "evaluaciones" ADD FOREIGN KEY ("leccion_id") REFERENCES "lecciones" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "preguntas_evaluacion" ADD FOREIGN KEY ("evaluacion_id") REFERENCES "evaluaciones" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "opciones_pregunta" ADD FOREIGN KEY ("pregunta_id") REFERENCES "preguntas_evaluacion" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "progreso_leccion" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "progreso_leccion" ADD FOREIGN KEY ("leccion_id") REFERENCES "lecciones" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resultados_evaluacion" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resultados_evaluacion" ADD FOREIGN KEY ("evaluacion_id") REFERENCES "evaluaciones" ("id") DEFERRABLE INITIALLY IMMEDIATE;
